bakeup/shop/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from bakeup.shop.views import (
    CustomerOrderListView,
    CustomerOrderTemplateDeleteView,
    CustomerOrderTemplateListView,
    ShopView,
    customer_order_add_or_update,
    customer_order_template_update,
    production_day_abo_products,
    redirect_to_production_day_view,
)
from bakeup.users.views import (
    LoginView,
    SignupView,
    UserProfileDeleteView,
    shop_user_update_view,
)

# from bakeup.workshop.views import ProductAddView, ProductDetailView, ProductListView


app_name = "shop"
urlpatterns = [
    path("<int:production_day>/", view=ShopView.as_view(), name="shop-production-day"),
    path(
        "redirect/",
        view=redirect_to_production_day_view,
        name="redirect-production-day",
    ),
    path(
        "orders/add/<int:production_day>/",
        view=customer_order_add_or_update,
        name="customer-order-add",
    ),
    path(_("orders/"), view=CustomerOrderListView.as_view(), name="order-list"),
    path(
        _("order-templates/<int:pk>/delete/"),
        view=CustomerOrderTemplateDeleteView.as_view(),
        name="customer-order-template-delete",
    ),
    path(
        _("order-templates/positions/<int:pk>/update/"),
        view=customer_order_template_update,
        name="customer-order-template-update",
    ),
    path(
        _("order-templates/"),
        view=CustomerOrderTemplateListView.as_view(),
        name="order-template-list",
    ),
    path("profile/", view=shop_user_update_view, name="user-profile"),
    path(_("login/"), view=LoginView.as_view(), name="login"),
    path(_("signup/<slug:token>/"), view=SignupView.as_view(), name="signup"),
    path(_("signup/"), view=SignupView.as_view(), name="signup"),
    path(
        _("account/closure/"),
        view=UserProfileDeleteView.as_view(),
        name="account-closure",
    ),
    path(
        "api/production-day-abo-products/<int:pk>/",
        view=production_day_abo_products,
        name="production-day-abo-products",
    ),
]

bakeup/users/urls.py
from django.urls import path

from bakeup.users.views import TokenLoginView, user_update_view

app_name = "users"
urlpatterns = [
    path("update/", view=user_update_view, name="update"),
    path("token/<slug:token>/", TokenLoginView.as_view(), name="login-token"),
    path("token/", TokenLoginView.as_view(), name="login-token"),
]

bakeup/workshop/urls.py
from django.urls import path

from bakeup.core.views import TagAutocomplete
from bakeup.workshop.exports import (
    CustomerBillbeeExportView,
    CustomerOrderBillbeeExportView,
    CustomerOrderEasyBillExportView,
    CustomerReady2OrderExportView,
    CustomerSevdeskExportView,
    ProductionDayExportView,
)
from bakeup.workshop.views import (
    BatchCustomerTemplateView,
    CategoryAddView,
    CategoryDeleteView,
    CategoryListView,
    CategoryUpdateView,
    CreateUpdateInstructionsView,
    CustomerAutocomplete,
    CustomerDeleteView,
    CustomerDetailView,
    CustomerListView,
    CustomerOrderBatchView,
    CustomerOrderCreateView,
    CustomerOrderDeleteView,
    CustomerOrderListView,
    CustomerOrderTemplateOverview,
    CustomerOrderUpdateView,
    CustomerUpdateView,
    GroupCreateView,
    GroupDeleteView,
    GroupListView,
    GroupUpdateView,
    PointOfSaleCreateView,
    PointOfSaleDeleteView,
    PointOfSaleListView,
    PointOfSaleUpdateView,
    ProductAddView,
    ProductDeleteView,
    ProductDetailView,
    ProductHierarchyDeleteView,
    ProductHierarchyUpdateView,
    ProductionDayAddView,
    ProductionDayCopyView,
    ProductionDayDeleteView,
    ProductionDayDetailView,
    ProductionDayListView,
    ProductionDayMetaProductView,
    ProductionDayProductDeleteView,
    ProductionDayReminderDeleteView,
    ProductionDayReminderView,
    ProductionDayUpdateView,
    ProductionPlanAddView,
    ProductionPlanDeleteView,
    ProductionPlanDetailView,
    ProductionPlanListView,
    ProductionPlanOfProductionDay,
    ProductListView,
    ProductUpdateView,
    RecipeDetailView,
    RecipeListView,
    TagAddView,
    TagDeleteView,
    TagListView,
    TagUpdateView,
    WorkshopView,
    customer_order_all_picked_up_view,
    customer_order_toggle_picked_up_view,
    order_max_quantities_view,
    pos_order_all_picked_up_view,
    product_add_inline_view,
    product_normalize_view,
    production_day_redirect_view,
    production_plan_cancel_view,
    production_plan_finish_view,
    production_plan_redirect_view,
    production_plan_start_view,
    production_plan_update,
    production_plans_finish_view,
    production_plans_start_view,
    reminder_message_redirect_view,
)

app_name = "workshop"
urlpatterns = [
    path("", view=WorkshopView.as_view(), name="workshop"),
    path("products/add/<int:pk>/", view=ProductAddView.as_view(), name="product-add"),
    path("products/add/", view=ProductAddView.as_view(), name="product-add"),
    path(
        "products/<int:pk>/delete/",
        view=ProductDeleteView.as_view(),
        name="product-delete",
    ),
    path(
        "products/<int:pk>/update/",
        view=ProductUpdateView.as_view(),
        name="product-update",
    ),
    path(
        "products/<int:pk>/normalize/",
        view=product_normalize_view,
        name="product-normalize",
    ),
    path("products/<int:pk>/", view=ProductDetailView.as_view(), name="product-detail"),
    path(
        "products/<int:pk>/add/",
        view=product_add_inline_view,
        name="product-add-inline",
    ),
    path(
        "products/<int:pk>/instructions/",
        view=CreateUpdateInstructionsView.as_view(),
        name="product-instructions-update",
    ),
    path("products/", view=ProductListView.as_view(), name="product-list"),
    path("recipes/<int:pk>/", view=RecipeDetailView.as_view(), name="recipe-detail"),
    path("recipes/", view=RecipeListView.as_view(), name="recipe-list"),
    path(
        "products/hierarchy/<int:pk>/delete/",
        view=ProductHierarchyDeleteView.as_view(),
        name="product-hierarchy-delete",
    ),
    path(
        "products/hierarchy/<int:pk>/update/",
        view=ProductHierarchyUpdateView.as_view(),
        name="product-hierarchy-update",
    ),
    path("categories/", view=CategoryListView.as_view(), name="category-list"),
    path("categories/add/", view=CategoryAddView.as_view(), name="category-add"),
    path(
        "categories/<int:pk>/update/",
        view=CategoryUpdateView.as_view(),
        name="category-update",
    ),
    path(
        "categories/<int:pk>/delete/",
        view=CategoryDeleteView.as_view(),
        name="category-delete",
    ),
    path("tags/", view=TagListView.as_view(), name="tag-list"),
    path("tags/add/", view=TagAddView.as_view(), name="tag-add"),
    path(
        "tags/<int:pk>/update/",
        view=TagUpdateView.as_view(),
        name="tag-update",
    ),
    path(
        "tags/<int:pk>/delete/",
        view=TagDeleteView.as_view(),
        name="tag-delete",
    ),
    path(
        "production-plans/",
        view=production_plan_redirect_view,
        name="production-plan-next",
    ),
    path(
        "production-plans/production-day/<int:pk>/",
        view=ProductionPlanOfProductionDay.as_view(),
        name="production-plan-production-day",
    ),
    path(
        "production-plans/list/",
        view=ProductionPlanListView.as_view(),
        name="production-plan-list",
    ),
    path(
        "production-plans/<int:pk>/",
        view=ProductionPlanDetailView.as_view(),
        name="production-plan-detail",
    ),
    path(
        "production-plans/<int:production_day>/start-all/",
        view=production_plans_start_view,
        name="production-plans-start",
    ),
    path(
        "production-plans/<int:production_day>/finish-all/",
        view=production_plans_finish_view,
        name="production-plans-finish",
    ),
    path(
        "production-plans/<int:pk>/finish/",
        view=production_plan_finish_view,
        name="production-plan-finish",
    ),
    path(
        "production-plans/<int:pk>/start/",
        view=production_plan_start_view,
        name="production-plan-start",
    ),
    path(
        "production-plans/<int:pk>/cancel/",
        view=production_plan_cancel_view,
        name="production-plan-cancel",
    ),
    path(
        "production-plans/<int:pk>/delete/",
        view=ProductionPlanDeleteView.as_view(),
        name="production-plan-delete",
    ),
    path(
        "production-plans/<int:pk>/update/",
        view=production_plan_update,
        name="production-plan-update",
    ),
    path(
        "production-plans/add/",
        view=ProductionPlanAddView.as_view(),
        name="production-plan-add",
    ),
    path(
        "production-days/",
        view=production_day_redirect_view,
        name="production-day-next",
    ),
    path(
        "production-days/list/",
        view=ProductionDayListView.as_view(),
        name="production-day-list",
    ),
    path(
        "production-days/add/",
        view=ProductionDayAddView.as_view(),
        name="production-day-add",
    ),
    path(
        "production-days/<int:pk>/copy/",
        view=ProductionDayCopyView.as_view(),
        name="production-day-copy",
    ),
    path(
        "production-days/<int:pk>/",
        view=ProductionDayDetailView.as_view(),
        name="production-day-detail",
    ),
    path(
        "production-days/<int:pk>/export/",
        view=ProductionDayExportView.as_view(),
        name="production-day-export",
    ),
    path(
        "production-days/<int:pk>/update/",
        view=ProductionDayUpdateView.as_view(),
        name="production-day-update",
    ),
    path(
        "production-days/<int:pk>/delete/",
        view=ProductionDayDeleteView.as_view(),
        name="production-day-delete",
    ),
    path(
        "production-days/<int:pk>/abo/",
        view=ProductionDayMetaProductView.as_view(),
        name="production-day-meta-product",
    ),
    path(
        "production-days/<int:production_day>/reminder/<int:pk>/",
        view=ProductionDayReminderView.as_view(),
        name="production-day-reminder",
    ),
    path(
        "production-days/<int:production_day>/reminder/<int:pk>/delete/",
        view=ProductionDayReminderDeleteView.as_view(),
        name="production-day-reminder-delete",
    ),
    path(
        "production-days/<int:production_day>/reminder/",
        view=ProductionDayReminderView.as_view(),
        name="production-day-reminder",
    ),
    path(
        "production-days/<int:pk>/select-reminder/",
        view=reminder_message_redirect_view,
        name="reminder-message-redirect",
    ),
    path(
        "production-days/<int:pk>/all-picked-up/",
        view=customer_order_all_picked_up_view,
        name="production-day-all-picked-up",
    ),
    path(
        "production-days/<int:pk>/order-max-quantities/",
        view=order_max_quantities_view,
        name="production-day-order-max-quantities",
    ),
    path(
        "production-days/<int:production_day>/<int:pos>/all-picked-up/",
        view=pos_order_all_picked_up_view,
        name="pos-all-picked-up",
    ),
    path(
        "production-day-product/<int:pk>/delete/",
        view=ProductionDayProductDeleteView.as_view(),
        name="production-day-product-delete",
    ),
    path("orders/", view=CustomerOrderListView.as_view(), name="order-list"),
    path("orders/batch/", view=CustomerOrderBatchView.as_view(), name="order-batch"),
    path(
        "orders/export/billbee/",
        view=CustomerOrderBillbeeExportView.as_view(),
        name="order-export-billbee",
    ),
    path(
        "orders/export/easybill/",
        view=CustomerOrderEasyBillExportView.as_view(),
        name="order-export-easybill",
    ),
    path(
        "orders/batch/<int:pk>/",
        view=CustomerOrderBatchView.as_view(),
        name="order-batch",
    ),
    path(
        "orders/<int:pk>/delete/",
        view=CustomerOrderDeleteView.as_view(),
        name="order-delete",
    ),
    path(
        "orders/<int:pk>/update/",
        view=CustomerOrderUpdateView.as_view(),
        name="order-update",
    ),
    path(
        "orders/add/<int:production_day>/",
        view=CustomerOrderCreateView.as_view(),
        name="order-add",
    ),
    path(
        "orders/<int:pk>/is-picked-up/",

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import RedirectView
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

from bakeup.core.views import HomeView
from bakeup.users.views import LoginView, SignupView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    # path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # path("impressum/", TemplateView.as_view(template_name="pages/impressum.html"), name="impressum"),
    # path("datenschutz/", TemplateView.as_view(template_name="pages/datenschutz.html"), name="datenschutz"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("accounts/login/", view=LoginView.as_view(), name="login"),
    path("accounts/signup/", view=SignupView.as_view(), name="signup"),
    path("accounts/", include("allauth.urls")),
    path("users/", include("bakeup.users.urls", namespace="users")),
    path("workshop/", include("bakeup.workshop.urls", namespace="workshop")),
    path("shop/", include("bakeup.shop.urls", namespace="shop")),
    path("newsletter/", include("bakeup.newsletter.urls", namespace="newsletter")),
    path("shop/", include(wagtail_urls)),
    # path("login/", LoginView.as_view(), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "favicon.ico/", RedirectView.as_view(url="/static/images/favicons/favicon.ico")
    ),
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path(
        "non-admin-draftail/",
        include(
            "wagtail_non_admin_draftail.urls", namespace="wagtail_non_admin_draftail"
        ),
    ),
    path("hijack/", include("hijack.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

bakeup/contrib/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import gettext_lazy as _

from bakeup.core.models import CommonBaseClass


# TODO: finish fields!
class Address(models.Model):
    address = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "Address"
        verbose_name_plural = "Addresses"

    def __str__(self):
        return self.address


class Note(CommonBaseClass):
    content = models.TextField(verbose_name=_("Note"))
    user = models.ForeignKey("users.User", on_delete=models.CASCADE)

    # Generic relation fields
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    def __str__(self):
        return self.content

bakeup/pages/views.py
# Create your views here.

bakeup/templates/workshop/batch_customerorder_form.html
{% extends "workshop/base.html" %}
{% load i18n %}
{% load django_bootstrap5 %}

{% block title %}{% trans "Update orders" %}{% endblock %}
{% block page_heading %}
{% trans "Update orders for" %} <small class="text-muted">{{ production_day }}</small>
{% endblock %}

{% block page_content %}
<div class="row">
  <div class="col col-sm-12">
    <form class="form-horizontal" method="post">
      {% csrf_token %}
      <div class="row mb-4">
        <div class="col">
          <div class="control-group">
            <div class="controls">
              <button type="submit" class="btn btn-primary float-end" name="add-new">
                {% trans "Update orders" %}
              </button>
              {% if next %}
              <a href="{{ next }}" class="btn btn-outline-primary float-end me-2">
              {% else %}
              <a href="{% url 'workshop:production-day-list' %}" class="btn btn-outline-primary float-end me-2">
              {% endif %}{% trans "Cancel" %}</a>
            </div>
          </div>
          </div>
      </div>
      <input type="hidden" name="next" value="{{ next }}" />
      {{ formset.management_form }}
      <div class="card p-3 mb-3 formset-container">
      {% for form in formset %}
        <div class="formset">
          <div class="row">
            <div class="col">
              {% if forloop.first %}
              <label class="form-label fw-bold">{% trans "Customer" %}</label>
              {% endif %}
              {% bootstrap_field form.customer_name show_label='skip' %}
              {% bootstrap_field form.customer show_label='skip' %}
            </div>
            {% for field in form.get_product_fields %}
            <div class="col">
              {% if forloop.parentloop.first %}
                {% bootstrap_field field label_class='fw-bold' %}
              {% else %}
                {% bootstrap_field field show_label='skip' %}
              {% endif %}
              </div>
            {% endfor %}
          </div>
        </div>
        {% endfor %}
        <span id="formset-before-element"></span>
      </div>
      <div class="row mt-4">
        <div class="col">
          <div class="control-group">
            <div class="controls">
              <button type="submit" class="btn btn-primary float-end" name="add-new">
                {% trans "Update orders" %}
              </button>
              {% if next %}
              <a href="{{ next }}" class="btn btn-outline-primary float-end me-2">
              {% else %}
              <a href="{% url 'workshop:production-day-list' %}" class="btn btn-outline-primary float-end me-2">
              {% endif %}{% trans "Cancel" %}</a>
            </div>
          </div>
          </div>
      </div>
    </form>
  </div>
</div>
{% include "workshop/includes/formset.html" %}
{% endblock %}

bakeup/templates/workshop/category_confirm_delete.html
{% extends "workshop/base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block page_heading %}{% trans "Delete category" %}:  {{ object }}{% endblock page_heading %}

{% block page_content %}
<div id="content-container" class="container p-none">
    <div class="side-p">
        {% if protected %}
        {% blocktranslate trimmed %}
        <p>The deletion of the selected object: <strong>{{ object }}</strong> would require first the deletion of the protected related objects:</p>
        {% endblocktranslate %}
            <p>
                <ul>
                    {% for item in protected %}
                    <li>{{ item|verbose_name }}: <a href="{% url 'workshop:product-detail' pk=item.pk %}">{{ item }}</a></li>
                    {% endfor %}
                </ul>
            </p>
        {% else %}
        <h3>{% trans "Are you sure?" %}</h3>
        {% blocktranslate trimmed %}
        <p>You're about to delete the following category: <strong>{{ object }}</strong>. Please confirm.</p>
        {% endblocktranslate %}
        <form action="" method="post">
            {% csrf_token %}
            <input class="btn btn-link"
                   type="button" value="{% trans 'Cancel' %}"
                   onclick="window.history.go(-1);"/>
            <input class="btn btn-primary" type="submit" value="{% trans 'Confirm' %}"/>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}

bakeup/templates/workshop/order_list.html
{% extends "workshop/base.html" %}
{% load django_bootstrap5 %}
{% load export_url from django_tables2 %}
{% load render_table from django_tables2 %}
{% load i18n %}

{% block title %}{% endblock %}
{% block page_heading %}{% trans "Orders" %}{% endblock %}

{% block page_heading_action %}
<form action="{% url 'workshop:order-batch' %}" method="post">
  {% csrf_token %}
  <div class="row justify-content-end">
    <div class="col-10 text-end">
      <div class="btn-group">
        <a class="btn btn-sm btn-primary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fas fa-file-download"></i> {% trans "Export as CSV" %}
        </a>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="{% export_url "csv" %}">{% trans "Export as CSV" %}</a></li>
          <li><a class="dropdown-item" href="{% url 'workshop:order-export-easybill' %}?{{ request.GET.urlencode }}">{% trans "Export easybill" %}</a></li>
        </ul>
      </div>
    </div>
  </div>
  </form>
{% endblock %}

{% block page_content %}
  {% if filter %}
  <form action="" method="get" class="form form-inline d-print-none">
    <div class="row justify-content-end g-2 mb-3">
      <div class="col-2">
        {% bootstrap_field filter.form.search size='sm' wrapper_class='' layout='horizontal' show_label=False horizontal_field_class='col-12' %}
      </div>
      <div class="col-2">
        {% bootstrap_field filter.form.customer size='sm' wrapper_class='' layout='horizontal' show_label=False horizontal_field_class='col-12' %}
      </div>
      <div class="col-2">
        {% bootstrap_field filter.form.point_of_sale size='sm' wrapper_class='' layout='horizontal' show_label=False horizontal_field_class='col-12' %}
      </div>
      <div class="col-2">
        {% bootstrap_field filter.form.month size='sm' wrapper_class='' layout='horizontal' show_label=False horizontal_field_class='col-12' %}
      </div>
      <div class="col-2">
        {% bootstrap_field filter.form.production_day size='sm' wrapper_class='' layout='horizontal' show_label=False horizontal_field_class='col-12' %}
      </div>
      <div class="col-auto">
        {% bootstrap_button "Filter" button_type="submit" button_class="btn-primary" size="sm" %}
        <button type="submit" name="reset-filters" class="btn btn-outline-primary btn-sm"><i class="fas fa-times"></i> {% trans "Reset" %}</button>
      </div>
    </div>

  </form>
  {% endif %}
  {% render_table table %}


{% endblock %}

bakeup/templates/workshop/product_list.html
{% extends "workshop/base.html" %}
{% load i18n %}
{% load django_bootstrap5 %}
{% load render_table from django_tables2 %}

{% block title %}{{ object_name_plural }}{% endblock %}
{% block page_heading %}{{ object_name_plural }}{% endblock page_heading %}


{% block page_heading_action %}
<a href="{% url 'workshop:product-add' %}" class="btn btn-primary btn-sm float-end">{% blocktrans %}Add new {{ object_name }} {% endblocktrans %}</a>
{% endblock page_heading_action %}

{% block page_content %}
  {% if filter %}
  <form action="" method="get" class="form form-inline">
    <div class="row justify-content-end mb-3">
      <div class="col-3">
        {% bootstrap_field filter.form.search size='sm' wrapper_class='' layout='horizontal' show_label=False horizontal_field_class='col-12' %}
      </div>
      <div class="col-3">
        {% bootstrap_field filter.form.category size='sm' wrapper_class='' layout='horizontal' show_label=False horizontal_field_class='col-12' %}
      </div>
      <div class="col-3">
        {% bootstrap_field filter.form.tag size='sm' wrapper_class='' layout='horizontal' show_label=False horizontal_field_class='col-12' %}
      </div>
      <div class="col-auto">
        {% bootstrap_button "Filter" button_type="submit" button_class="btn-outline-primary" size="sm" %}
        <button type="submit" name="reset-filters" class="btn btn-outline-primary btn-sm"><i class="fas fa-times"></i> {% trans "Reset filters" %}</button>
      </div>
    </div>

  </form>
  {% endif %}
  {% render_table table %}


{% endblock %}

bakeup/templates/workshop/productionplan_list.html
{% extends "workshop/base.html" %}
{% load crispy_forms_tags %}
{% load django_bootstrap5 %}
{% load i18n %}
{% block title %}{% trans "Production plans" %}{% endblock %}
{% block page_heading %}
<span class="d-print-none">{% trans "Production plans" %} <small class="text-muted">{{ day_of_sale_selected }}</small></span>
{% endblock %}
{% block page_heading_action %}
<a href="{% url 'workshop:production-plan-add' %}" class="btn btn-primary btn-sm float-end me-2">{% trans "Add or update production plans" %}</a>
{% endblock%}

{% block page_content %}
<div class="row mt-2 mb-4">
  <div class="col-8">
    <h6 class="d-none d-print-block">{% trans "Production plans" %} {{ day_of_sale_selected }}</h6>
  </div>
</div>
  {% if filter %}
  <form action="" method="get" class="form form-inline d-print-none">
    <div class="row justify-content-end">
      <div class="col-6 text-end align-middle">
        {% for choice in filter.form.state.field.widget.choices %}
        <div class="form-check form-check-inline">
          <input class="form-check-input" name="state" type="checkbox" id="productionPlanState{{ choice.0 }}" value="{{ choice.0 }}"{% if choice.0|stringformat:"i" in filter.form.state.value %} checked{% endif %}>
          <label class="form-check-label" for="productionPlanState{{ choice.0 }}">{{ choice.1 }}</label>
        </div>
        {% endfor %}
      </div>
      <div class="col-3">
        {% bootstrap_field filter.form.production_day size='sm' wrapper_class='' layout='horizontal' show_label=False horizontal_field_class='col-12' success_css_class='' %}
      </div>
      <div class="col-2">
        {% bootstrap_button "Filter" button_type="submit" button_class="btn-outline-primary" size="sm" %}
        <button type="submit" name="reset-filters" class="btn btn-outline-primary btn-sm"><i class="fas fa-times"></i> {% trans "Reset filters" %}</button>
      </div>
    </div>
  </form>
  {% endif %}
<div class="row">
  <div class="col">
    {% include "workshop/includes/production_plan_table.html" with production_plans=production_plans %}
  </div>
</div>

{% endblock %}

bakeup/templates/workshop/tag_confirm_delete.html
{% extends "workshop/base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block page_heading %}{% trans "Delete tag" %}:  {{ object }}{% endblock page_heading %}

{% block page_content %}
<div id="content-container" class="container p-none">
    <div class="side-p">
        {% if protected %}
        {% blocktranslate trimmed %}
        <p>The deletion of the selected object: <strong>{{ object }}</strong> would require first the deletion of the protected related objects:</p>
        {% endblocktranslate %}
            <p>
                <ul>
                    {% for item in protected %}
                    <li>{{ item|verbose_name }}: <a href="{% url 'workshop:product-detail' pk=item.pk %}">{{ item }}</a></li>
                    {% endfor %}
                </ul>
            </p>
        {% else %}
        <h3>{% trans "Are you sure?" %}</h3>
        {% blocktranslate trimmed %}
        <p>You're about to delete the following tag: <strong>{{ object }}</strong>. Please confirm.</p>
        {% endblocktranslate %}
        <form action="" method="post">
            {% csrf_token %}
            <input class="btn btn-link"
                   type="button" value="{% trans 'Cancel' %}"
                   onclick="window.history.go(-1);"/>
            <input class="btn btn-primary" type="submit" value="{% trans 'Confirm' %}"/>
        </form>
        {% endif %}
    </div>
</div>
{% endblock %}