bakeup/shop/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from bakeup.shop.views import (
    CustomerOrderListView,
    CustomerOrderTemplateDeleteView,
    CustomerOrderTemplateListView,
    ShopView,
    customer_order_add_or_update,
    customer_order_template_update,
    production_day_abo_products,
    redirect_to_production_day_view,
)
from bakeup.users.views import (
    LoginView,
    SignupView,
    UserProfileDeleteView,
    shop_user_update_view,
)

# from bakeup.workshop.views import ProductAddView, ProductDetailView, ProductListView


app_name = "shop"
urlpatterns = [
    path("<int:production_day>/", view=ShopView.as_view(), name="shop-production-day"),
    path(
        "redirect/",
        view=redirect_to_production_day_view,
        name="redirect-production-day",
    ),
    path(
        "orders/add/<int:production_day>/",
        view=customer_order_add_or_update,
        name="customer-order-add",
    ),
    path(_("orders/"), view=CustomerOrderListView.as_view(), name="order-list"),
    path(
        _("order-templates/<int:pk>/delete/"),
        view=CustomerOrderTemplateDeleteView.as_view(),
        name="customer-order-template-delete",
    ),
    path(
        _("order-templates/positions/<int:pk>/update/"),
        view=customer_order_template_update,
        name="customer-order-template-update",
    ),
    path(
        _("order-templates/"),
        view=CustomerOrderTemplateListView.as_view(),
        name="order-template-list",
    ),
    path("profile/", view=shop_user_update_view, name="user-profile"),
    path(_("login/"), view=LoginView.as_view(), name="login"),
    path(_("signup/<slug:token>/"), view=SignupView.as_view(), name="signup"),
    path(_("signup/"), view=SignupView.as_view(), name="signup"),
    path(
        _("account/closure/"),
        view=UserProfileDeleteView.as_view(),
        name="account-closure",
    ),
    path(
        "api/production-day-abo-products/<int:pk>/",
        view=production_day_abo_products,
        name="production-day-abo-products",
    ),
]

bakeup/users/urls.py
from django.urls import path

from bakeup.users.views import TokenLoginView, user_update_view

app_name = "users"
urlpatterns = [
    path("update/", view=user_update_view, name="update"),
    path("token/<slug:token>/", TokenLoginView.as_view(), name="login-token"),
    path("token/", TokenLoginView.as_view(), name="login-token"),
]

bakeup/workshop/urls.py
from django.urls import path

from bakeup.core.views import TagAutocomplete
from bakeup.workshop.exports import (
    CustomerBillbeeExportView,
    CustomerOrderBillbeeExportView,
    CustomerOrderEasyBillExportView,
    CustomerReady2OrderExportView,
    CustomerSevdeskExportView,
    ProductionDayExportView,
)
from bakeup.workshop.views import (
    BatchCustomerTemplateView,
    CategoryAddView,
    CategoryDeleteView,
    CategoryListView,
    CategoryUpdateView,
    CreateUpdateInstructionsView,
    CustomerAutocomplete,
    CustomerDeleteView,
    CustomerDetailView,
    CustomerListView,
    CustomerOrderBatchView,
    CustomerOrderCreateView,
    CustomerOrderDeleteView,
    CustomerOrderListView,
    CustomerOrderTemplateOverview,
    CustomerOrderUpdateView,
    CustomerUpdateView,
    GroupCreateView,
    GroupDeleteView,
    GroupListView,
    GroupUpdateView,
    PointOfSaleCreateView,
    PointOfSaleDeleteView,
    PointOfSaleListView,
    PointOfSaleUpdateView,
    ProductAddView,
    ProductDeleteView,
    ProductDetailView,
    ProductHierarchyDeleteView,
    ProductHierarchyUpdateView,
    ProductionDayAddView,
    ProductionDayCopyView,
    ProductionDayDeleteView,
    ProductionDayDetailView,
    ProductionDayListView,
    ProductionDayMetaProductView,
    ProductionDayProductDeleteView,
    ProductionDayReminderDeleteView,
    ProductionDayReminderView,
    ProductionDayUpdateView,
    ProductionPlanAddView,
    ProductionPlanDeleteView,
    ProductionPlanDetailView,
    ProductionPlanListView,
    ProductionPlanOfProductionDay,
    ProductListView,
    ProductUpdateView,
    RecipeDetailView,
    RecipeListView,
    TagAddView,
    TagDeleteView,
    TagListView,
    TagUpdateView,
    WorkshopView,
    customer_order_all_picked_up_view,
    customer_order_toggle_picked_up_view,
    order_max_quantities_view,
    pos_order_all_picked_up_view,
    product_add_inline_view,
    product_normalize_view,
    production_day_redirect_view,
    production_plan_cancel_view,
    production_plan_finish_view,
    production_plan_redirect_view,
    production_plan_start_view,
    production_plan_update,
    production_plans_finish_view,
    production_plans_start_view,
    reminder_message_redirect_view,
)

app_name = "workshop"
urlpatterns = [
    path("", view=WorkshopView.as_view(), name="workshop"),
    path("products/add/<int:pk>/", view=ProductAddView.as_view(), name="product-add"),
    path("products/add/", view=ProductAddView.as_view(), name="product-add"),
    path(
        "products/<int:pk>/delete/",
        view=ProductDeleteView.as_view(),
        name="product-delete",
    ),
    path(
        "products/<int:pk>/update/",
        view=ProductUpdateView.as_view(),
        name="product-update",
    ),
    path(
        "products/<int:pk>/normalize/",
        view=product_normalize_view,
        name="product-normalize",
    ),
    path("products/<int:pk>/", view=ProductDetailView.as_view(), name="product-detail"),
    path(
        "products/<int:pk>/add/",
        view=product_add_inline_view,
        name="product-add-inline",
    ),
    path(
        "products/<int:pk>/instructions/",
        view=CreateUpdateInstructionsView.as_view(),
        name="product-instructions-update",
    ),
    path("products/", view=ProductListView.as_view(), name="product-list"),
    path("recipes/<int:pk>/", view=RecipeDetailView.as_view(), name="recipe-detail"),
    path("recipes/", view=RecipeListView.as_view(), name="recipe-list"),
    path(
        "products/hierarchy/<int:pk>/delete/",
        view=ProductHierarchyDeleteView.as_view(),
        name="product-hierarchy-delete",
    ),
    path(
        "products/hierarchy/<int:pk>/update/",
        view=ProductHierarchyUpdateView.as_view(),
        name="product-hierarchy-update",
    ),
    path("categories/", view=CategoryListView.as_view(), name="category-list"),
    path("categories/add/", view=CategoryAddView.as_view(), name="category-add"),
    path(
        "categories/<int:pk>/update/",
        view=CategoryUpdateView.as_view(),
        name="category-update",
    ),
    path(
        "categories/<int:pk>/delete/",
        view=CategoryDeleteView.as_view(),
        name="category-delete",
    ),
    path("tags/", view=TagListView.as_view(), name="tag-list"),
    path("tags/add/", view=TagAddView.as_view(), name="tag-add"),
    path(
        "tags/<int:pk>/update/",
        view=TagUpdateView.as_view(),
        name="tag-update",
    ),
    path(
        "tags/<int:pk>/delete/",
        view=TagDeleteView.as_view(),
        name="tag-delete",
    ),
    path(
        "production-plans/",
        view=production_plan_redirect_view,
        name="production-plan-next",
    ),
    path(
        "production-plans/production-day/<int:pk>/",
        view=ProductionPlanOfProductionDay.as_view(),
        name="production-plan-production-day",
    ),
    path(
        "production-plans/list/",
        view=ProductionPlanListView.as_view(),
        name="production-plan-list",
    ),
    path(
        "production-plans/<int:pk>/",
        view=ProductionPlanDetailView.as_view(),
        name="production-plan-detail",
    ),
    path(
        "production-plans/<int:production_day>/start-all/",
        view=production_plans_start_view,
        name="production-plans-start",
    ),
    path(
        "production-plans/<int:production_day>/finish-all/",
        view=production_plans_finish_view,
        name="production-plans-finish",
    ),
    path(
        "production-plans/<int:pk>/finish/",
        view=production_plan_finish_view,
        name="production-plan-finish",
    ),
    path(
        "production-plans/<int:pk>/start/",
        view=production_plan_start_view,
        name="production-plan-start",
    ),
    path(
        "production-plans/<int:pk>/cancel/",
        view=production_plan_cancel_view,
        name="production-plan-cancel",
    ),
    path(
        "production-plans/<int:pk>/delete/",
        view=ProductionPlanDeleteView.as_view(),
        name="production-plan-delete",
    ),
    path(
        "production-plans/<int:pk>/update/",
        view=production_plan_update,
        name="production-plan-update",
    ),
    path(
        "production-plans/add/",
        view=ProductionPlanAddView.as_view(),
        name="production-plan-add",
    ),
    path(
        "production-days/",
        view=production_day_redirect_view,
        name="production-day-next",
    ),
    path(
        "production-days/list/",
        view=ProductionDayListView.as_view(),
        name="production-day-list",
    ),
    path(
        "production-days/add/",
        view=ProductionDayAddView.as_view(),
        name="production-day-add",
    ),
    path(
        "production-days/<int:pk>/copy/",
        view=ProductionDayCopyView.as_view(),
        name="production-day-copy",
    ),
    path(
        "production-days/<int:pk>/",
        view=ProductionDayDetailView.as_view(),
        name="production-day-detail",
    ),
    path(
        "production-days/<int:pk>/export/",
        view=ProductionDayExportView.as_view(),
        name="production-day-export",
    ),
    path(
        "production-days/<int:pk>/update/",
        view=ProductionDayUpdateView.as_view(),
        name="production-day-update",
    ),
    path(
        "production-days/<int:pk>/delete/",
        view=ProductionDayDeleteView.as_view(),
        name="production-day-delete",
    ),
    path(
        "production-days/<int:pk>/abo/",
        view=ProductionDayMetaProductView.as_view(),
        name="production-day-meta-product",
    ),
    path(
        "production-days/<int:production_day>/reminder/<int:pk>/",
        view=ProductionDayReminderView.as_view(),
        name="production-day-reminder",
    ),
    path(
        "production-days/<int:production_day>/reminder/<int:pk>/delete/",
        view=ProductionDayReminderDeleteView.as_view(),
        name="production-day-reminder-delete",
    ),
    path(
        "production-days/<int:production_day>/reminder/",
        view=ProductionDayReminderView.as_view(),
        name="production-day-reminder",
    ),
    path(
        "production-days/<int:pk>/select-reminder/",
        view=reminder_message_redirect_view,
        name="reminder-message-redirect",
    ),
    path(
        "production-days/<int:pk>/all-picked-up/",
        view=customer_order_all_picked_up_view,
        name="production-day-all-picked-up",
    ),
    path(
        "production-days/<int:pk>/order-max-quantities/",
        view=order_max_quantities_view,
        name="production-day-order-max-quantities",
    ),
    path(
        "production-days/<int:production_day>/<int:pos>/all-picked-up/",
        view=pos_order_all_picked_up_view,
        name="pos-all-picked-up",
    ),
    path(
        "production-day-product/<int:pk>/delete/",
        view=ProductionDayProductDeleteView.as_view(),
        name="production-day-product-delete",
    ),
    path("orders/", view=CustomerOrderListView.as_view(), name="order-list"),
    path("orders/batch/", view=CustomerOrderBatchView.as_view(), name="order-batch"),
    path(
        "orders/export/billbee/",
        view=CustomerOrderBillbeeExportView.as_view(),
        name="order-export-billbee",
    ),
    path(
        "orders/export/easybill/",
        view=CustomerOrderEasyBillExportView.as_view(),
        name="order-export-easybill",
    ),
    path(
        "orders/batch/<int:pk>/",
        view=CustomerOrderBatchView.as_view(),
        name="order-batch",
    ),
    path(
        "orders/<int:pk>/delete/",
        view=CustomerOrderDeleteView.as_view(),
        name="order-delete",
    ),
    path(
        "orders/<int:pk>/update/",
        view=CustomerOrderUpdateView.as_view(),
        name="order-update",
    ),
    path(
        "orders/add/<int:production_day>/",
        view=CustomerOrderCreateView.as_view(),
        name="order-add",
    ),
    path(
        "orders/<int:pk>/is-picked-up/",

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import RedirectView
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

from bakeup.core.views import HomeView
from bakeup.users.views import LoginView, SignupView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    # path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # path("impressum/", TemplateView.as_view(template_name="pages/impressum.html"), name="impressum"),
    # path("datenschutz/", TemplateView.as_view(template_name="pages/datenschutz.html"), name="datenschutz"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("accounts/login/", view=LoginView.as_view(), name="login"),
    path("accounts/signup/", view=SignupView.as_view(), name="signup"),
    path("accounts/", include("allauth.urls")),
    path("users/", include("bakeup.users.urls", namespace="users")),
    path("workshop/", include("bakeup.workshop.urls", namespace="workshop")),
    path("shop/", include("bakeup.shop.urls", namespace="shop")),
    path("newsletter/", include("bakeup.newsletter.urls", namespace="newsletter")),
    path("shop/", include(wagtail_urls)),
    # path("login/", LoginView.as_view(), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "favicon.ico/", RedirectView.as_view(url="/static/images/favicons/favicon.ico")
    ),
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path(
        "non-admin-draftail/",
        include(
            "wagtail_non_admin_draftail.urls", namespace="wagtail_non_admin_draftail"
        ),
    ),
    path("hijack/", include("hijack.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

bakeup/contrib/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import gettext_lazy as _

from bakeup.core.models import CommonBaseClass


# TODO: finish fields!
class Address(models.Model):
    address = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "Address"
        verbose_name_plural = "Addresses"

    def __str__(self):
        return self.address


class Note(CommonBaseClass):
    content = models.TextField(verbose_name=_("Note"))
    user = models.ForeignKey("users.User", on_delete=models.CASCADE)

    # Generic relation fields
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    def __str__(self):
        return self.content

bakeup/pages/views.py
# Create your views here.

bakeup/templates/workshop/includes/dashboard.html
{% load i18n %}

<div class="row mt-4 mb-4">
    <div class="col-12 col-lg-6 offset-lg-1 mb-lg-0 mb-4">
        <div class="card h-100">
            <h4 class="card-header text-bg-dark"><i class="fa-solid fa-calendar-day fa-sm"></i> {% trans "Next production days" %} <small class="text-muted">{{ upcoming_production_days_count }}</small></h4>
            <div class="card-body p-0">
              {% include "workshop/includes/dashboard_production_days.html" with production_days=upcoming_production_days %}
            </div>
            <div class="card-footer">
              <a href="{% url 'workshop:production-day-next' %}" class="btn btn-sm btn-outline-primary">{% trans "All production days" %}</a>
              <a href="{% url 'workshop:production-day-add' %}" class="btn btn-sm btn-outline-primary">{% trans "Add production day" %}</a>
            </div>
        </div>
    </div>
    <div class="col-12 col-lg-4 mb-lg-0 mb-4">
        <div class="card h-100">
          <h4 class="card-header text-bg-dark"><i class="fa-solid fa-calendar-day fa-sm"></i> {% trans "Past production days" %} <small class="text-muted">{{ past_production_days_count }}</small></h4>
            <div class="card-body p-0">
              {% include "workshop/includes/dashboard_production_days.html" with production_days=past_production_days %}
            </div>
        </div>
    </div>
</div>
<div class="row mt-4 mb-4">
  <div class="col-12 col-lg-6 offset-lg-1 mb-lg-0 mb-4">
      <div class="card h-100">
        <h4 class="card-header text-bg-dark"><i class="fa-solid fa-sliders fa-sm"></i> {% trans "Production Plans" %}</h4>
          <div class="card-body p-0">
            <table class="table table-hover table-sm table-striped m-0">
              <tr>
                <th>{% trans "Day" %}</th>
                <th>{% trans "Qty" %}</th>
                <th>{% trans "Product" %}</th>
              </tr>
            {% for production_plan in production_plans %}
              <tr style="transform: rotate(0);">
                <td>{{ production_plan.production_day.day_of_sale|date:'d.m.' }}</td>
                <td>{{ production_plan.quantity|floatformat }}x</td>
                <td><a class="stretched-link" href="{% url 'workshop:production-plan-production-day' pk=production_plan.production_day.pk %}#production-plan-{{ production_plan.pk }}">{{ production_plan.product }}</a></span> ({{ production_plan.quantity|multiply:production_plan.product.weight|floatformat:0 }} g) {% include "workshop/includes/production_plan_state.html" with state_css_class=production_plan.get_state_css_class label=production_plan.get_state_display_value %}</td>
              </tr>
              {% endfor %}
          </table>
          </div>
          <div class="card-footer">
            <a href="{% url 'workshop:production-day-next' %}" class="btn btn-sm btn-outline-primary">{% trans "Go to production plans" %}</a>
          </div>
      </div>
  </div>
  <div class="col-12 col-lg-4 mb-lg-0 mb-4">
    <div class="card h-100">
      <h4 class="card-header text-bg-dark"><i class="fas fa-warehouse fa-sm"></i> {% trans "Points of sale" %} <small class="text-muted">{{ points_of_sale.count }}</small></h4>
        <div class="card-body p-0">
          <table class="table table-sm table-striped m-0">
            <tr>
              <th>{% trans "Point of sale" %}</th>
              <th>{% trans "Customers" %}</th>
              <th>{% trans "Orders" %}</th>
              <th></th>
            </tr>
          {% for point_of_sale in points_of_sale %}
            <tr>
              <td>{{ point_of_sale }}</td>
              <td>{{ point_of_sale.get_customer_count }}</td>
              <td>{{ point_of_sale.get_orders_count }}</td>
              <td></td>
            </tr>
            {% endfor %}
        </table>
        </div>
        <div class="card-footer">
          <a href="{% url 'workshop:point-of-sale-list' %}" class="btn btn-sm btn-outline-primary">{% trans "Go to points of sale" %}</a>
        </div>
    </div>
</div>
</div>
<div class="row mt-4 mb-4">
    <div class="col-12 col-sm-3 offset-sm-1 mb-sm-0 mb-4">
        <div class="card">
            <div class="card-body">
              <h4 class="card-title">{% trans "Customers" %} <small class="text-muted">{{ customers_count }}</small></h4>
              <p class="card-text"></p>
              <a href="{% url 'workshop:customer-list' %}" class="btn btn-sm btn-outline-primary">{% trans "Go to customers" %}</a>
            </div>
        </div>
    </div>
    <div class="col-12 col-sm-3 mb-sm-0 mb-4">
        <div class="card">
            <div class="card-body">
              <h4 class="card-title">{% trans "Orders" %} <small class="text-muted">{{ orders_count }}</small></h4>
              <p class="card-text"></p>
              <a href="{% url 'workshop:order-list' %}" class="btn btn-sm btn-outline-primary">{% trans "Go to orders" %}</a>
            </div>
        </div>
    </div>
    <div class="col-12 col-sm-3 mb-sm-0 mb-4">
        <div class="card">
            <div class="card-body">
              <h4 class="card-title">{% trans "Recurring orders" %} <small class="text-muted">{{ recurring_orders_count }}</small></h4>
              <p class="card-text"></p>
              <a href="{% url 'workshop:order-list' %}" class="btn btn-sm btn-outline-primary">{% trans "Go to recurring orders" %}</a>
            </div>
        </div>
    </div>
</div>
<div class="row mt-4 mb-4">
    <div class="col-12 col-sm-3 offset-sm-1 mb-sm-0 mb-4">
        <div class="card">
            <div class="card-body">
              <h4 class="card-title">{% trans "Categories" %} <small class="text-muted">{{ categories_count }}</small></h4>
              <p class="card-text"></p>
              <a href="{% url 'workshop:category-list' %}" class="btn btn-sm btn-outline-primary">{% trans "Go to categories" %}</a>
            </div>
        </div>
    </div>
    <div class="col-12 col-sm-3 mb-sm-0 mb-4">
        <div class="card">
            <div class="card-body">
              <h4 class="card-title">{% trans "Recipes" %} <small class="text-muted">{{ recipies_count }}</small></h4>
              <p class="card-text"></p>
              <a href="{% url 'workshop:recipe-list' %}" class="btn btn-sm btn-outline-primary">{% trans "Go to recipies" %}</a>
            </div>
        </div>
    </div>
    <div class="col-12 col-sm-3 mb-sm-0">
        <div class="card">
            <div class="card-body">
              <h4 class="card-title">{% trans "Products" %} <small class="text-muted">{{ products_count }}</small></h4>
              <p class="card-text"></p>
              <a href="{% url 'workshop:product-list' %}" class="btn btn-sm btn-outline-primary">{% trans "Go to products" %}</a>
            </div>
        </div>
    </div>
</div>

bakeup/templates/workshop/includes/order_positions.html
<ul class="list-unstyled mb-0">
    {% for position in positions %}
    <li><span class="quantity">{{ position.quantity}} x</span> {{ position.product }}{% if position.price_total %}<small class="text-muted"> {{ position.price_total }}</small>{% endif %}{% if not position.production_plan.is_produced %} {% include "workshop/includes/production_plan_state.html" with state_css_class=position.production_plan.get_state_css_class label=position.production_plan.get_state_display_value %}{% endif %}</li>
    {% endfor %}
</ul>

bakeup/templates/workshop/includes/sidebar.html
{% load i18n utils %}
<button class="sidebar-toggler d-print-none" type="button" aria-controls="plattform-menu" aria-expanded="false" aria-label="Toggle plattform navigation">
  <i class="fas fa-list fa-fw"></i>
</button>
<div class="sidebar col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark d-print-none position-fixed">
  <nav class="d-flex flex-column align-items-center align-items-sm-start min-vh-100 py-3">
    {% include "includes/logo.html" with logo_size='large' home_url='home' client_logo=settings.pages.BrandSettings.logo %}
      <span class="sidebar-toggler-hide"><i class="fas fa-chevron-left"></i></span>
      <h3 class="mt-1 mb-3 text-center text-light w-100">{{ request.tenant.name }}</h3>
          <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-start w-100">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'workshop:workshop' %}"><i class="fa-solid fa-house fa-fw"></i> {% translate "Dashboard" %}</a>
            </li>
            {% if request.user.is_authenticated and request.user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'workshop:category-list' %}"><i class="fa-solid fa-list fa-fw"></i> {% translate "Categories" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'workshop:tag-list' %}"><i class="fa-solid fa-tags fa-fw"></i> {% translate "Tags" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'workshop:recipe-list' %}"><i class="fa-solid fa-book fa-fw"></i> {% translate "Recipes" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'workshop:product-list' %}"><i class="fa-solid fa-atom fa-fw"></i> {% translate "Products" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'workshop:production-day-next' %}"><i class="fa-solid fa-calendar-day fa-fw"></i> {% translate "Production Days" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'workshop:production-plan-next' %}"><i class="fa-solid fa-sliders fa-fw"></i> {% translate "Production Plans" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'workshop:order-list' %}"><i class="fa-solid fa-shopping-basket fa-fw"></i> {% translate "Orders" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'workshop:customer-order-template-overview' %}"><i class="fas fa-repeat fa-fw"></i> {% trans "Subscriptions" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'workshop:customer-list' %}"><i class="fas fa-user fa-fw"></i> {% translate "Customers" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'workshop:point-of-sale-list' %}"><i class="fas fa-warehouse fa-fw"></i> {% translate "Points of sale" %}</a>
            </li>
            {% endif %}
          </ul>
          <ul class="nav nav-pills flex-column mb-0 align-items-start w-100">
            {% if request.user.is_authenticated and request.user.is_customer %}
            <li class="nav-item">
              <a class="nav-link" href="/shop/"><i class="fa-solid fa-shop"></i> {% translate "Shop" %}</a>
            </li>
            {% endif %}
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'wagtailadmin_home' %}"><i class="fa-solid fa-file-lines fa-fw"></i> {% translate "CMS" %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:update' %}"><i class="fa-solid fa-user fa-fw"></i> {% translate "Profile" %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}"><i class="fa-solid fa-right-from-bracket fa-fw"></i> {% translate "Logout" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}"><i class="fa-solid fa-right-to-bracket fa-fw"></i> {% translate "Login" %}</a>
              </li>
            {% endif %}
          </ul>
         <p class="small text-white mb-0 mt-2 text-center w-100">Gebacken mit <a href="https://bakeup.org" class="fw-bold">bakeup.org</a> | <a href="https://github.com/bruecksen/bakeup/releases/latest" target="_blank">{% current_git_tag %}</a></p>
        </nav>
</div>