bakeup/shop/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from bakeup.shop.views import (
    CustomerOrderListView,
    CustomerOrderTemplateDeleteView,
    CustomerOrderTemplateListView,
    ShopView,
    customer_order_add_or_update,
    customer_order_template_update,
    production_day_abo_products,
    redirect_to_production_day_view,
)
from bakeup.users.views import (
    LoginView,
    SignupView,
    UserProfileDeleteView,
    shop_user_update_view,
)

# from bakeup.workshop.views import ProductAddView, ProductDetailView, ProductListView


app_name = "shop"
urlpatterns = [
    path("<int:production_day>/", view=ShopView.as_view(), name="shop-production-day"),
    path(
        "redirect/",
        view=redirect_to_production_day_view,
        name="redirect-production-day",
    ),
    path(
        "orders/add/<int:production_day>/",
        view=customer_order_add_or_update,
        name="customer-order-add",
    ),
    path(_("orders/"), view=CustomerOrderListView.as_view(), name="order-list"),
    path(
        _("order-templates/<int:pk>/delete/"),
        view=CustomerOrderTemplateDeleteView.as_view(),
        name="customer-order-template-delete",
    ),
    path(
        _("order-templates/positions/<int:pk>/update/"),
        view=customer_order_template_update,
        name="customer-order-template-update",
    ),
    path(
        _("order-templates/"),
        view=CustomerOrderTemplateListView.as_view(),
        name="order-template-list",
    ),
    path("profile/", view=shop_user_update_view, name="user-profile"),
    path(_("login/"), view=LoginView.as_view(), name="login"),
    path(_("signup/<slug:token>/"), view=SignupView.as_view(), name="signup"),
    path(_("signup/"), view=SignupView.as_view(), name="signup"),
    path(
        _("account/closure/"),
        view=UserProfileDeleteView.as_view(),
        name="account-closure",
    ),
    path(
        "api/production-day-abo-products/<int:pk>/",
        view=production_day_abo_products,
        name="production-day-abo-products",
    ),
]

bakeup/users/urls.py
from django.urls import path

from bakeup.users.views import TokenLoginView, user_update_view

app_name = "users"
urlpatterns = [
    path("update/", view=user_update_view, name="update"),
    path("token/<slug:token>/", TokenLoginView.as_view(), name="login-token"),
    path("token/", TokenLoginView.as_view(), name="login-token"),
]

bakeup/workshop/urls.py
from django.urls import path

from bakeup.core.views import TagAutocomplete
from bakeup.workshop.exports import (
    CustomerBillbeeExportView,
    CustomerOrderBillbeeExportView,
    CustomerOrderEasyBillExportView,
    CustomerReady2OrderExportView,
    CustomerSevdeskExportView,
    ProductionDayExportView,
)
from bakeup.workshop.views import (
    BatchCustomerTemplateView,
    CategoryAddView,
    CategoryDeleteView,
    CategoryListView,
    CategoryUpdateView,
    CreateUpdateInstructionsView,
    CustomerAutocomplete,
    CustomerDeleteView,
    CustomerDetailView,
    CustomerListView,
    CustomerOrderBatchView,
    CustomerOrderCreateView,
    CustomerOrderDeleteView,
    CustomerOrderListView,
    CustomerOrderTemplateOverview,
    CustomerOrderUpdateView,
    CustomerUpdateView,
    GroupCreateView,
    GroupDeleteView,
    GroupListView,
    GroupUpdateView,
    PointOfSaleCreateView,
    PointOfSaleDeleteView,
    PointOfSaleListView,
    PointOfSaleUpdateView,
    ProductAddView,
    ProductDeleteView,
    ProductDetailView,
    ProductHierarchyDeleteView,
    ProductHierarchyUpdateView,
    ProductionDayAddView,
    ProductionDayCopyView,
    ProductionDayDeleteView,
    ProductionDayDetailView,
    ProductionDayListView,
    ProductionDayMetaProductView,
    ProductionDayProductDeleteView,
    ProductionDayReminderDeleteView,
    ProductionDayReminderView,
    ProductionDayUpdateView,
    ProductionPlanAddView,
    ProductionPlanDeleteView,
    ProductionPlanDetailView,
    ProductionPlanListView,
    ProductionPlanOfProductionDay,
    ProductListView,
    ProductUpdateView,
    RecipeDetailView,
    RecipeListView,
    TagAddView,
    TagDeleteView,
    TagListView,
    TagUpdateView,
    WorkshopView,
    customer_order_all_picked_up_view,
    customer_order_toggle_picked_up_view,
    order_max_quantities_view,
    pos_order_all_picked_up_view,
    product_add_inline_view,
    product_normalize_view,
    production_day_redirect_view,
    production_plan_cancel_view,
    production_plan_finish_view,
    production_plan_redirect_view,
    production_plan_start_view,
    production_plan_update,
    production_plans_finish_view,
    production_plans_start_view,
    reminder_message_redirect_view,
)

app_name = "workshop"
urlpatterns = [
    path("", view=WorkshopView.as_view(), name="workshop"),
    path("products/add/<int:pk>/", view=ProductAddView.as_view(), name="product-add"),
    path("products/add/", view=ProductAddView.as_view(), name="product-add"),
    path(
        "products/<int:pk>/delete/",
        view=ProductDeleteView.as_view(),
        name="product-delete",
    ),
    path(
        "products/<int:pk>/update/",
        view=ProductUpdateView.as_view(),
        name="product-update",
    ),
    path(
        "products/<int:pk>/normalize/",
        view=product_normalize_view,
        name="product-normalize",
    ),
    path("products/<int:pk>/", view=ProductDetailView.as_view(), name="product-detail"),
    path(
        "products/<int:pk>/add/",
        view=product_add_inline_view,
        name="product-add-inline",
    ),
    path(
        "products/<int:pk>/instructions/",
        view=CreateUpdateInstructionsView.as_view(),
        name="product-instructions-update",
    ),
    path("products/", view=ProductListView.as_view(), name="product-list"),
    path("recipes/<int:pk>/", view=RecipeDetailView.as_view(), name="recipe-detail"),
    path("recipes/", view=RecipeListView.as_view(), name="recipe-list"),
    path(
        "products/hierarchy/<int:pk>/delete/",
        view=ProductHierarchyDeleteView.as_view(),
        name="product-hierarchy-delete",
    ),
    path(
        "products/hierarchy/<int:pk>/update/",
        view=ProductHierarchyUpdateView.as_view(),
        name="product-hierarchy-update",
    ),
    path("categories/", view=CategoryListView.as_view(), name="category-list"),
    path("categories/add/", view=CategoryAddView.as_view(), name="category-add"),
    path(
        "categories/<int:pk>/update/",
        view=CategoryUpdateView.as_view(),
        name="category-update",
    ),
    path(
        "categories/<int:pk>/delete/",
        view=CategoryDeleteView.as_view(),
        name="category-delete",
    ),
    path("tags/", view=TagListView.as_view(), name="tag-list"),
    path("tags/add/", view=TagAddView.as_view(), name="tag-add"),
    path(
        "tags/<int:pk>/update/",
        view=TagUpdateView.as_view(),
        name="tag-update",
    ),
    path(
        "tags/<int:pk>/delete/",
        view=TagDeleteView.as_view(),
        name="tag-delete",
    ),
    path(
        "production-plans/",
        view=production_plan_redirect_view,
        name="production-plan-next",
    ),
    path(
        "production-plans/production-day/<int:pk>/",
        view=ProductionPlanOfProductionDay.as_view(),
        name="production-plan-production-day",
    ),
    path(
        "production-plans/list/",
        view=ProductionPlanListView.as_view(),
        name="production-plan-list",
    ),
    path(
        "production-plans/<int:pk>/",
        view=ProductionPlanDetailView.as_view(),
        name="production-plan-detail",
    ),
    path(
        "production-plans/<int:production_day>/start-all/",
        view=production_plans_start_view,
        name="production-plans-start",
    ),
    path(
        "production-plans/<int:production_day>/finish-all/",
        view=production_plans_finish_view,
        name="production-plans-finish",
    ),
    path(
        "production-plans/<int:pk>/finish/",
        view=production_plan_finish_view,
        name="production-plan-finish",
    ),
    path(
        "production-plans/<int:pk>/start/",
        view=production_plan_start_view,
        name="production-plan-start",
    ),
    path(
        "production-plans/<int:pk>/cancel/",
        view=production_plan_cancel_view,
        name="production-plan-cancel",
    ),
    path(
        "production-plans/<int:pk>/delete/",
        view=ProductionPlanDeleteView.as_view(),
        name="production-plan-delete",
    ),
    path(
        "production-plans/<int:pk>/update/",
        view=production_plan_update,
        name="production-plan-update",
    ),
    path(
        "production-plans/add/",
        view=ProductionPlanAddView.as_view(),
        name="production-plan-add",
    ),
    path(
        "production-days/",
        view=production_day_redirect_view,
        name="production-day-next",
    ),
    path(
        "production-days/list/",
        view=ProductionDayListView.as_view(),
        name="production-day-list",
    ),
    path(
        "production-days/add/",
        view=ProductionDayAddView.as_view(),
        name="production-day-add",
    ),
    path(
        "production-days/<int:pk>/copy/",
        view=ProductionDayCopyView.as_view(),
        name="production-day-copy",
    ),
    path(
        "production-days/<int:pk>/",
        view=ProductionDayDetailView.as_view(),
        name="production-day-detail",
    ),
    path(
        "production-days/<int:pk>/export/",
        view=ProductionDayExportView.as_view(),
        name="production-day-export",
    ),
    path(
        "production-days/<int:pk>/update/",
        view=ProductionDayUpdateView.as_view(),
        name="production-day-update",
    ),
    path(
        "production-days/<int:pk>/delete/",
        view=ProductionDayDeleteView.as_view(),
        name="production-day-delete",
    ),
    path(
        "production-days/<int:pk>/abo/",
        view=ProductionDayMetaProductView.as_view(),
        name="production-day-meta-product",
    ),
    path(
        "production-days/<int:production_day>/reminder/<int:pk>/",
        view=ProductionDayReminderView.as_view(),
        name="production-day-reminder",
    ),
    path(
        "production-days/<int:production_day>/reminder/<int:pk>/delete/",
        view=ProductionDayReminderDeleteView.as_view(),
        name="production-day-reminder-delete",
    ),
    path(
        "production-days/<int:production_day>/reminder/",
        view=ProductionDayReminderView.as_view(),
        name="production-day-reminder",
    ),
    path(
        "production-days/<int:pk>/select-reminder/",
        view=reminder_message_redirect_view,
        name="reminder-message-redirect",
    ),
    path(
        "production-days/<int:pk>/all-picked-up/",
        view=customer_order_all_picked_up_view,
        name="production-day-all-picked-up",
    ),
    path(
        "production-days/<int:pk>/order-max-quantities/",
        view=order_max_quantities_view,
        name="production-day-order-max-quantities",
    ),
    path(
        "production-days/<int:production_day>/<int:pos>/all-picked-up/",
        view=pos_order_all_picked_up_view,
        name="pos-all-picked-up",
    ),
    path(
        "production-day-product/<int:pk>/delete/",
        view=ProductionDayProductDeleteView.as_view(),
        name="production-day-product-delete",
    ),
    path("orders/", view=CustomerOrderListView.as_view(), name="order-list"),
    path("orders/batch/", view=CustomerOrderBatchView.as_view(), name="order-batch"),
    path(
        "orders/export/billbee/",
        view=CustomerOrderBillbeeExportView.as_view(),
        name="order-export-billbee",
    ),
    path(
        "orders/export/easybill/",
        view=CustomerOrderEasyBillExportView.as_view(),
        name="order-export-easybill",
    ),
    path(
        "orders/batch/<int:pk>/",
        view=CustomerOrderBatchView.as_view(),
        name="order-batch",
    ),
    path(
        "orders/<int:pk>/delete/",
        view=CustomerOrderDeleteView.as_view(),
        name="order-delete",
    ),
    path(
        "orders/<int:pk>/update/",
        view=CustomerOrderUpdateView.as_view(),
        name="order-update",
    ),
    path(
        "orders/add/<int:production_day>/",
        view=CustomerOrderCreateView.as_view(),
        name="order-add",
    ),
    path(
        "orders/<int:pk>/is-picked-up/",

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import RedirectView
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

from bakeup.core.views import HomeView
from bakeup.users.views import LoginView, SignupView

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    # path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # path("impressum/", TemplateView.as_view(template_name="pages/impressum.html"), name="impressum"),
    # path("datenschutz/", TemplateView.as_view(template_name="pages/datenschutz.html"), name="datenschutz"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("accounts/login/", view=LoginView.as_view(), name="login"),
    path("accounts/signup/", view=SignupView.as_view(), name="signup"),
    path("accounts/", include("allauth.urls")),
    path("users/", include("bakeup.users.urls", namespace="users")),
    path("workshop/", include("bakeup.workshop.urls", namespace="workshop")),
    path("shop/", include("bakeup.shop.urls", namespace="shop")),
    path("newsletter/", include("bakeup.newsletter.urls", namespace="newsletter")),
    path("shop/", include(wagtail_urls)),
    # path("login/", LoginView.as_view(), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "favicon.ico/", RedirectView.as_view(url="/static/images/favicons/favicon.ico")
    ),
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path(
        "non-admin-draftail/",
        include(
            "wagtail_non_admin_draftail.urls", namespace="wagtail_non_admin_draftail"
        ),
    ),
    path("hijack/", include("hijack.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

bakeup/contrib/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import gettext_lazy as _

from bakeup.core.models import CommonBaseClass


# TODO: finish fields!
class Address(models.Model):
    address = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "Address"
        verbose_name_plural = "Addresses"

    def __str__(self):
        return self.address


class Note(CommonBaseClass):
    content = models.TextField(verbose_name=_("Note"))
    user = models.ForeignKey("users.User", on_delete=models.CASCADE)

    # Generic relation fields
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    def __str__(self):
        return self.content

bakeup/pages/views.py
# Create your views here.

bakeup/templates/shop/base.html
{% extends "base.html" %}

{% load utils%}
{% block theme %}
  {% include 'shop/includes/theme.html' %}
{% endblock %}
{% block body_class %}shop{% endblock %}
{% block content %}
{% block header %}
{% include "shop/includes/header.html" %}
{% endblock header %}
{% block jumbotron %}
{% endblock jumbotron %}
<div class="container mb-4">
  {% block page_header %}
  <div class="row mt-2">
    <div class="col-8">
      <div class="page-heading p-4">
        <h1>{% block page_heading %}{% endblock page_heading %}</h1>
      </div>
    </div>
    <div class="col align-self-center d-print-none">
      {% block page_heading_action %}{% endblock page_heading_action%}
    </div>
  </div>
  {% endblock page_header %}
  {% block page_content_container %}
  <div class="row justify-content-center">
    <div class="col-12 col-xl-10">
      {% block page_content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock page_content %}
      </div>
  </div>
  {% endblock page_content_container %}
</div>
{% endblock content %}

{% block footer %}
{% include 'shop/includes/footer.html' %}
{% endblock footer %}

bakeup/templates/shop/base_page.html
{% extends "shop/base.html" %}

{% block header %}
{% include "shop/includes/header.html" with background=True %}
{% endblock header %}

{% block page_header %}
{% endblock page_header %}

{% block title %}{{ request.tenant.name }} - {% if page.seo_title %}{{ page.seo_title }}{% else %}{{ page.title }}{% endif %}{% endblock title %}
{% block og_title %}{{ request.tenant.name }} - {% if page.seo_title %}{{ page.seo_title }}{% else %}{{ page.title }}{% endif %}{% endblock og_title %}
{% block description %}{{ page.search_description }}{% endblock description %}
{% block og_description %}{{ page.search_description }}{% endblock og_description %}

{% block page_content_container %}
<div class="row justify-content-center">
  <div class="col-12 col-md-10 mt-5">
    {% block page_content %}
      <p>Use this document as a way to quick start any new project.</p>
    {% endblock page_content %}
    </div>
</div>
{% endblock page_content_container %}

bakeup/templates/shop/customer_order_list.html
{% extends "shop/base_page.html" %}
{% load utils %}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}

{% block title %}{{ request.tenant.name }} - Bestellungen{% endblock %}
{% block page_heading %}Bestellungen{% endblock %}

{% block page_content %}
{% if abos %}
<div class="row">
  <div class="col-12 col-lg-10">
    {% for order in abos %}
    <div class="card px-3 py-2 mb-5" id="bestellung-{{ order.pk }}">
      <h2>Abo <span class="badge rounded-pill text-bg-secondary fs-6">{{ order.get_state }}</span></h2>
        <p>Das Abo umfasst die folgenden Produkte:</p>
        <div class="row">
            <div class="col-12 col-lg-8">
                <table class="table table-light">
                    <thead>
                      <tr>
                        <th scope="col">Menge</th>
                        <th scope="col">Gebäck</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for position in order.positions.all %}
                            <tr>
                            <td>{{ position.quantity }}x</td>
                            <td>{{ position.product.get_display_name }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                  {% if order.is_running %}
                  <a class="btn btn-outline-primary fw-bold" href="{% url 'shop:customer-order-template-delete' pk=order.pk %}">Abo beenden</a>
                  <a class="btn btn-primary fw-bold" data-bs-toggle="modal" data-bs-target="#modal-order-template-{{ order.id }}">Abo ändern</a>
                  {% endif %}
            </div>
        </div>
    </div>
    {% include "shop/includes/checkout_abo.html" with name='abo' display_all=True id=order.id customer_order=order products=order.positions.all %}

    {% empty %}
    <p class="mt-4">Bisher liegen noch keine Abos vor.</p>
    {% endfor %}
  </div>
</div>
{% endif %}

<h2 class="mb-3">Bestellübersicht</h2>
<div class="row">
  <div class="col-12 col-lg-10">
    {% for order in object_list %}
    {% with has_price=order.price_total %}
    <div class="card px-3 py-2 mb-5" id="bestellung-{{ order.pk }}">
        <h4 class="fs-5">Backtag: <strong>{{ order.production_day }}</strong></h4>
        <h4 class="fs-5">Abholung: <strong>{{ order.point_of_sale.name|default:'-' }}</strong></h4>
        <div class="row">
            <div class="col-12">
                <table class="table table-light">
                    <thead>
                      <tr>
                        <th scope="col">Menge</th>
                        <th scope="col">Gebäck</th>
                        <th scope="col">Status</th>
                        {% if order.has_abo %}<th scope="col">Abo</th>{% endif %}
                        {% if has_price %}<th class="price-column" scope="col">Preis</th>{% endif %}
                      </tr>
                    </thead>
                    <tbody>
                        {% for position in order.positions.all %}
                            <tr>
                            <td>{{ position.quantity }}x</td>
                            <td>{{ position.product.get_display_name }}</td>

                            <td>{% include "workshop/includes/production_plan_state.html" with state_css_class=position.production_plan.get_state_css_class label=position.production_plan.get_state_display_value %}</td>
                            {% if order.has_abo %}
                            <td>
                              {% if position.customer_order_template_positions.exists %}
                                <a href="{% url 'shop:order-template-list' %}" data-bs-container="body" data-bs-trigger="hover focus" data-bs-toggle="popover" data-bs-placement="top" data-bs-content="Du hast dieses Produkt {{ position.customer_order_template_positions.first.quantity }}x abonniert."><span class="badge rounded-pill text-bg-primary">{{ position.customer_order_template_positions.first.quantity }}x</span></a>
                              {% endif %}
                            </td>
                            {% endif %}
                            {% if has_price %}
                            <td>
                                {% if position.price_total %}
                                <nobr><span class="sale-price">{{ position.price_total.amount }}</span> €</nobr>
                                {% else %}
                                -
                                {% endif %}
                            </td>
                            {% endif %}
                            </tr>
                        {% endfor %}
                        {% if has_price %}
                        <tr class="border-top border-3 price border-white">
                            <td colspan="3"></td>{% if order.has_abo %}<td></td>{% endif %}<td><strong><nobr class="price-total"><span>{{ order.price_total }}</span> €</nobr></strong></td>
                        </tr>
                        {% endif %}
                    </tbody>
                  </table>
                  {% if not order.is_locked %}
                  <a class="btn btn-outline-primary fw-bold" data-bs-toggle="modal" data-bs-target="#modal-order-{{ order.id }}">Bestellung ändern</a>
                  {% endif %}
            </div>
        </div>
    </div>

    {% include "shop/includes/checkout.html" with name='checkout' display_all=True customer_order=order production_day=order.production_day point_of_sales=order.production_day.point_of_sales.all id=order.id products=order.get_production_day_products_ordered_list next_url=next_url show_price=has_price %}
    {% endwith %}
    {% empty %}
    <p class="mt-4">Bisher liegen noch keine Bestellungen vor.</p>
    {% endfor %}
  </div>
</div>
{% endblock %}

bakeup/templates/shop/customer_order_template_list.html
{% extends "shop/base_page.html" %}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}

{% block title %}{{ request.tenant.name }} - Bestellungen{% endblock %}
{% block page_heading %}Bestellungen{% endblock %}

{% block page_content %}
<div class="row">
  <div class="col-12 col-lg-10">
    {% for order in object_list %}
    <div class="card px-3 py-2 mb-5" id="bestellung-{{ order.pk }}">
        <h2>Abo <span class="badge rounded-pill text-bg-secondary fs-6">{{ order.get_state }}</span></h2>
        <p>Das Abo umfasst die folgenden Produkte:</p>
        <div class="row">
            <div class="col-12 col-lg-8">
                <table class="table table-light">
                    <thead>
                      <tr>
                        <th scope="col">Menge</th>
                        <th scope="col">Gebäck</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for position in order.positions.all %}
                            <tr>
                            <td>{{ position.quantity }}x</td>
                            <td>{{ position.product.get_display_name }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                  {% if order.is_running %}
                  <a class="btn btn-outline-primary fw-bold" href="{% url 'shop:customer-order-template-delete' pk=order.pk %}">Abo beenden</a>
                  <a class="btn btn-primary fw-bold" data-bs-toggle="modal" data-bs-target="#modal-order-template-{{ order.id }}">Abo ändern</a>
                  {% endif %}
            </div>
        </div>
    </div>
    {% include "shop/includes/checkout_abo.html" with name='abo' display_all=True id=order.id customer_order=order products=order.positions.all %}

    {% empty %}
    <p class="mt-4">Bisher liegen noch keine Abos vor.</p>
    {% endfor %}
  </div>
</div>
{% endblock %}

bakeup/templates/shop/production_day.html
{% extends "shop/base_page.html" %}
{% load crispy_forms_tags %}

{% block title %}Shop{% endblock %}
{% block page_header %}{% endblock %}

{% block page_content %}

{% include "shop/includes/production_day_order.html" with production_day=production_day production_day_products=production_day_products %}
<div class="row">
  <div class="col">
    <div class="horizontal-ruler">
      <hr class="border border-dark border-3 opacity-100 w-100 position-absolute start-0">
    </div>
  </div>
</div>
<div class="row mb-3">
  <div class="col">
    <h2 id="backtage">Die nächsten Backtage</h2>
  </div>
</div>
{% include "shop/includes/production_days.html" with production_days=production_days %}

{% endblock %}

bakeup/templates/shop/weekly.html
{% extends "shop/base.html" %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load thumbnail %}

{% block title %}Shop{% endblock %}

{% block page_content %}
  <h1>{% translate "Shop" %}</h1>
  <div class="row justify-content-between mt-4 mb-4">
    <div class="col-4 col-sm-2"><a href="{% url 'shop:weekly' calendar_week=calendar_week.last.week year=calendar_week.last.year %}"><i class="fa-solid fa-chevron-left"></i> {% translate "Previous Week" %}</a></div>
    <div class="col-4 col-sm-2 text-center">
      {{ calendar_week.week }}<br \>
      &nbsp;
      {% if calendar_week_current  %}
      <a class="small" href="{% url 'shop:weekly' calendar_week=calendar_week_current.week year=calendar_week_current.year %}">{% translate "Jump to current week" %}</a>
      {% endif %}
    </div>
    <div class="col-4 col-sm-2 text-end"><a href="{% url 'shop:weekly' calendar_week=calendar_week.next.week year=calendar_week.next.year %}">{% translate "Next Week" %} <i class="fa-solid fa-chevron-right"></i></a></div>
  </div>
  <div class="row justify-content-between">
    {% for production_day, production_day_products in production_days.items %}
    <div class="col-12 col-sm-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ production_day.day_of_sale|date:'d.m.Y' }}</h5>
            {% if production_day_products %}
              <form class="form-horizontal" method="post" action="{% url 'shop:order-add' production_day=production_day.pk %}">
                {% csrf_token %}
                {% for production_day_product in production_day_products %}
                  <h5>{{ production_day_product.production_day_product.product.name }}</h5>
                  {% if production_day_product.production_day_product.product.image %}
                  {% thumbnail production_day_product.production_day_product.product.image "400" crop="center" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" class="img-thumbnail" alt="product image">
                  {% endthumbnail %}
                  {% endif %}
                  {{ production_day_product.form|crispy }}
                {% endfor %}
              <button type="submit" class="btn btn-primary"{% if not production_day.has_products_open_for_order %} disabled{% endif %}>{% translate "Submit order" %}</button>
              </form>
            {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <div class="row mt-4 mb-4">
    <div class="col">
    </div>
  </div>
{% endblock %}